name: bag_tagger
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0 
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  path: ^1.8.3
  uuid: ^4.0.0
  file_picker: ^5.3.1
  share_plus: ^7.0.2
  qr_flutter: ^4.1.0
  http: ^1.3.0
  package_info_plus: ^4.0.0
  
  # Firebase packages temporarily removed
  # firebase_core: ^2.21.0
  # cloud_firestore: ^4.12.2
  # firebase_auth: ^4.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true