/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt1KK1dk3dL9WX_hB2bDsSW15DDXS-ALs',
    appId: '1:391129058381:web:3491e5dc40e7c14d842004',
    messagingSenderId: '391129058381',
    projectId: 'bagtagger-9ae80',
    authDomain: 'bagtagger-9ae80.firebaseapp.com',
    storageBucket: 'bagtagger-9ae80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYO327HFTb77xs3rBdNjSKy4YtJtb0gE',
    appId: '1:391129058381:android:aa90897166702367842004',
    messagingSenderId: '391129058381',
    projectId: 'bagtagger-9ae80',
    storageBucket: 'bagtagger-9ae80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmHlQokbYCO8sUCWSfsc3dxopiDPc-pQ',
    appId: '1:391129058381:ios:0072ac2794c2d759842004',
    messagingSenderId: '391129058381',
    projectId: 'bagtagger-9ae80',
    storageBucket: 'bagtagger-9ae80.firebasestorage.app',
    iosBundleId: 'com.example.bagTagger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOmHlQokbYCO8sUCWSfsc3dxopiDPc-pQ',
    appId: '1:391129058381:ios:0072ac2794c2d759842004',
    messagingSenderId: '391129058381',
    projectId: 'bagtagger-9ae80',
    storageBucket: 'bagtagger-9ae80.firebasestorage.app',
    iosBundleId: 'com.example.bagTagger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt1KK1dk3dL9WX_hB2bDsSW15DDXS-ALs',
    appId: '1:391129058381:web:eca3feefa3cb8632842004',
    messagingSenderId: '391129058381',
    projectId: 'bagtagger-9ae80',
    authDomain: 'bagtagger-9ae80.firebaseapp.com',
    storageBucket: 'bagtagger-9ae80.firebasestorage.app',
  );
}
*/

// Empty placeholder to satisfy imports
class DefaultFirebaseOptions {
  // Empty implementation
}